language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.8
      env: TOXENV=py38

install:
    - pip install -U pip tox codecov

script: tox

after_success:
    - codecov
